config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
  resources :tasks
  resources :users, only: [:new,:create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 100 }
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include ApplicationHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success]="ログアウトしました。"
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_user_logged_in
    before_action :correct_user, only: [:show, :edit, :update, :destroy]
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    
    
    def index
        if logged_in?
            @tasks = current_user.tasks.all
        end
        #flashtest
        #index -> show , index -> edit なら flash情報が残ってた
        #index -> show -> edit なら index -> edit の段階でflash情報が消えた
        #flash.nowはどちらの場合でも消えた
        #画面更新でflashは消えるみたい
        #render アクション(ここなら'index')があると考えていい
    end
    
    def show
    end
    
    def new
        @task = current_user.tasks.new
    end
    
    def create
        @task = current_user.tasks.build(task_params)
        if @task.save
            flash[:success] = "Taskの登録に成功"
            redirect_to tasks_path
        else
            flash.now[:failed] = "Taskの登録に失敗"
            render :new
        end
    end
    
    def edit
    end
    
    def update

        if @task.update(task_params)
            flash[:success] = "Taskの更新に成功"
            redirect_to tasks_path
        else
            flash.now[:failed] = "Taskの更新に失敗"
            render :edit
        end
    end

    def destroy

        if @task.destroy
            flash[:success] = "Taskの削除に成功"
            redirect_to tasks_path
        else
            flash.now[:feild] = "Taskの削除に失敗"
            render :index
        end
    end
    
    private
    def flashtest
        flash[:test_redirect_to] = 'redirect_toされた'
        flash.now[:test_render] = 'renderされた'
    end

    def set_task
        @task = current_user.tasks.find(params[:id])
    end
    #Strong Parameter
    def task_params
        params.require(:task).permit(:content,:status)
    end
    
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to tasks_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/layouts/_flash_tasks.html.erb
<%#
Controllerでflash[ラベル]に当てた情報を表示、
多分flashはハッシュな感じ
%>

<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%#
アプリケーションの共通部、こんな感じでコメントするとソースに現れない
body部の yield に各viewの情報が乗る
%>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Tasklist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'tasks/navbar'%>
    
    <div class="container">
      <%= render 'layouts/flash_tasks' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    <%= form_for(task) do |f| %>
      <%#エラーに関する表記%>
      <% if task.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <%#フォーム%>
      <div class="form-group">
        <%= f.label :content, 'コンテンツ' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      
       <div class="form-group">
        <%= f.label :status, 'タイトル' %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.submit '投稿', class: 'btn btn-primary' %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/tasks/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
  	<div class="container">
  		<div class="navbar-header">
  			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-lesson10">
  				<span class="sr-only">Toggle navigation</span>
  				<span class="icon-bar"></span>
  				<span class="icon-bar"></span>
  				<span class="icon-bar"></span>
  			</button>
  			<a class="navbar-brand" href="/">Tasklist</a>
  		</div>
  		<div class="collapse navbar-collapse" id="navbar-lesson10">
  			<ul class="nav navbar-nav navbar-right">
	    		<%if logged_in? %>
	    		  <li><%= link_to current_user.name, '#' %></li>
    				<li><%= link_to '新規作成', new_task_path %></li>
    				<li><%= link_to 'Logout', logout_path, method: :delete %></li>
      		<% else%>
  			  <li><%= link_to 'Login', login_path %></li>
  				<% end %>
  				
  			</ul>
  		</div>
  		
  	</div>
  </nav>
</header>

app/views/tasks/edit.html.erb
<h1>Task更新ページ</h1>

<%= render 'form', task: @task%>
<%= link_to "go to top", tasks_path %>

app/views/tasks/index.html.erb
<%if logged_in? %>

    <h1>Task一覧ページ</h1>
    <%# flash[:view_flash]='indexのviewにflash'%>
    <%# flash.now[:view_flash_now]='indexのviewにflash.now'%>

    <ul>
        <% @tasks.each do |task|%>
        <li>
            <%= link_to task.id, task %>:
            <%= task.content%>&gt;
            <%= task.status%>
            <%= link_to "cng", edit_task_path(task)%>
            <%= link_to 'del', task, method: :delete, data: { confirm: 'Task消しちゃいますよ？' } %>
        </li>
        <% end %>
    </ul>
    
    <div>
        <%= link_to "新規Task登録", new_task_path %>
    </div>
<%else%>
    
  <div class="center jumbotron">
    <div class="text-center">
      <h1>I am Tasklist</h1>
      <%= link_to 'Please Login!', login_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
    
<%end%>

app/views/tasks/new.html.erb
<h1>新規Task登録ページ</h1>

<%= render 'form', task: @task %>

<%= link_to "go to top", tasks_path %>

app/views/tasks/show.html.erb
<h1>Task詳細ページ</h1>

<div>
    <p>投稿者:<%= @task.user.name%></p>
    <p>番号:<%= @task.id %></p>
    <p>内容:<%= @task.content %></p>
    <p>更新:<%= @task.updated_at %></p>
    <p>作成:<%= @task.created_at %></p>
</div>

<p><%= link_to "cange", edit_task_path(@task) %></p>
<p><%= link_to "delete", @task , method: :delete %></p>
<p><%= link_to "return to top_page", tasks_path %></p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>